---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: >
          (?x)^(
            test/(with-skip-tag-id|unicode).yml|
            examples/example.yml
          )$
        exclude_types: ['markdown']
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      #- id: no-commit-to-branch
        language_version: python3
